### PR TITLE
Decrease minimum home preset to 10W

### PR DESCRIPTION
**Pull request by andythomas**
This solves #107

### CODE REVIEW

**Review by thomluther — COMMENTED** [review]
What is the minimum allowed in the App?
Is it 10 or 0W in case nothing should be discharged for a certain interval?

**Review by thomluther — CHANGES_REQUESTED** [review]
We cannot change the PRESET_MIN, this is used as minimum values in various places for SB1 schedules and may break usage with SB1.
I found another place where to change the validation limits for the fields.

**Comment by thomluther** [comment]
Thanks for the suggested changes, but cannot change the constants for the minimums since this may break SB1 usage.
I fixed it in the validators for the services, which are defined in the const.py
```
VALID_APPLIANCE_LOAD = vol.Any(
    None,
    cv.ENTITY_MATCH_NONE,
    vol.All(
        vol.Coerce(int),
        vol.Range(
            #min=api.SolixDefaults.PRESET_MIN,  # Min for SB1 usable only
            min=0,
            max=api.SolixDefaults.PRESET_MAX * 2,
        ),
    ),
)
```

I also assume 0 W is the minimum that can be applied in the schedule, or is this really 10W? This would not allow to stop export for an interval???

**Comment by andythomas** [comment]
I did not want to confuse you with the 10W. I just looked at it from my personal use-case perspective. I have a base load of 95W and, therefore, have only one schedule 24/7 of a constant value. If it is 100W, I feed just a little bit into the grid at night, which I want to avoid. Consequently, I use 90W, 50W or whatever value will turn out to match my installation. Just 0W makes no sense **for me**, because I would basically not utilize the battery in its intended way. Certainly, other people might want 0W at certain times.

I tested the new version and it works nicely. It might be intentional, but the version number showing in the integration was not bumped. 

Thank you for all the work!

**Pull request closed without merging**
